

#ifndef MCAL_DIO_DIO_CONFIG_H_
#define MCAL_DIO_DIO_CONFIG_H_

#define DIO_PA_PIN0_DIR		OUTPUT
#define DIO_PA_PIN1_DIR		OUTPUT
#define DIO_PA_PIN2_DIR		OUTPUT
#define DIO_PA_PIN3_DIR		OUTPUT
#define DIO_PA_PIN4_DIR		OUTPUT
#define DIO_PA_PIN5_DIR		OUTPUT
#define DIO_PA_PIN6_DIR		OUTPUT
#define DIO_PA_PIN7_DIR		OUTPUT

#define DIO_PB_PIN0_DIR   	OUTPUT
#define DIO_PB_PIN1_DIR   	OUTPUT
#define DIO_PB_PIN2_DIR   	OUTPUT
#define DIO_PB_PIN3_DIR   	OUTPUT
#define DIO_PB_PIN4_DIR   	OUTPUT
#define DIO_PB_PIN5_DIR   	OUTPUT
#define DIO_PB_PIN6_DIR   	OUTPUT
#define DIO_PB_PIN7_DIR   	INPUT

#define DIO_PC_PIN0_DIR    	INPUT
#define DIO_PC_PIN1_DIR    	OUTPUT
#define DIO_PC_PIN2_DIR    	INPUT
#define DIO_PC_PIN3_DIR    	OUTPUT
#define DIO_PC_PIN4_DIR    	OUTPUT
#define DIO_PC_PIN5_DIR    	OUTPUT
#define DIO_PC_PIN6_DIR    	OUTPUT
#define DIO_PC_PIN7_DIR    	OUTPUT

#define DIO_PD_PIN0_DIR   	OUTPUT
#define DIO_PD_PIN1_DIR   	OUTPUT
#define DIO_PD_PIN2_DIR   	OUTPUT
#define DIO_PD_PIN3_DIR   	OUTPUT
#define DIO_PD_PIN4_DIR   	OUTPUT
#define DIO_PD_PIN5_DIR   	OUTPUT
#define DIO_PD_PIN6_DIR   	OUTPUT
#define DIO_PD_PIN7_DIR   	INPUT


#define DIO_PA_PIN0_VAL		LOW
#define DIO_PA_PIN1_VAL		LOW
#define DIO_PA_PIN2_VAL		LOW
#define DIO_PA_PIN3_VAL		LOW
#define DIO_PA_PIN4_VAL		LOW
#define DIO_PA_PIN5_VAL		LOW
#define DIO_PA_PIN6_VAL		LOW
#define DIO_PA_PIN7_VAL		LOW

#define DIO_PB_PIN0_VAL		LOW
#define DIO_PB_PIN1_VAL		LOW
#define DIO_PB_PIN2_VAL		LOW
#define DIO_PB_PIN3_VAL		LOW
#define DIO_PB_PIN4_VAL		LOW
#define DIO_PB_PIN5_VAL		LOW
#define DIO_PB_PIN6_VAL		LOW
#define DIO_PB_PIN7_VAL		LOW

#define DIO_PC_PIN0_VAL		LOW
#define DIO_PC_PIN1_VAL     LOW
#define DIO_PC_PIN2_VAL     LOW
#define DIO_PC_PIN3_VAL     LOW
#define DIO_PC_PIN4_VAL     LOW
#define DIO_PC_PIN5_VAL     LOW
#define DIO_PC_PIN6_VAL     LOW
#define DIO_PC_PIN7_VAL     LOW

#define DIO_PD_PIN0_VAL     LOW
#define DIO_PD_PIN1_VAL     LOW
#define DIO_PD_PIN2_VAL     LOW
#define DIO_PD_PIN3_VAL     LOW
#define DIO_PD_PIN4_VAL     LOW
#define DIO_PD_PIN5_VAL     LOW
#define DIO_PD_PIN6_VAL     LOW
#define DIO_PD_PIN7_VAL     LOW

#endif /* MCAL_DIO_DIO_CONFIG_H_ */
